spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8081

inventory-service:
  url: http://localhost:8082

springdocs:
  url:
    swagger-ui: /swagger-ui.html
  api-docs:
    path: /v3/api-docs