server:
  port: 9001
spring:
  application:
    name: product-service

  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/products?authSource=admin
springdocs:
  url:
    swagger-ui: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
