spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3307/inventories?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
server:
  port: 8082

springdocs:
  url:
    swagger-ui: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

